package com.vinoigitare.tools;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;

import com.vinoigitare.model.Song;
import com.vinoigitare.storage.TextFileSongRepository;

/**
 * Standalone CLI tool that splits a scanned/typed songbook PDF into
 * individual {@code .tab} files, using the same storage convention as
 * {@link TextFileSongRepository} (reused directly, not reimplemented).
 *
 * <p><b>This tool does not know or care what's inside any particular PDF.</b>
 * It was built and tested exclusively against a synthetic fixture PDF
 * generated by this project's own tests (see {@code SongbookPdfImporterTest}),
 * containing fictional made-up songs -- never against any real songbook.
 * Point it at material you actually have the rights to use; running it
 * against a scanned book of commercially published, copyrighted songs and
 * then distributing the output would not be. Personal, private use of your
 * own legally-obtained material is your call to make, not this tool's.
 *
 * <p><b>Song-boundary detection is a heuristic, not a parser.</b> Real
 * songbook layouts vary wildly. Two strategies are supported:
 * <ul>
 *   <li>{@code blank-lines} (default): treats a run of 2+ consecutive blank
 *       lines, anywhere in the extracted text, as a song separator. Page
 *       texts are joined with a single blank line (not two), so a song
 *       spanning a page boundary is not incorrectly split just because the
 *       page break happens mid-song -- but this also means if the source
 *       PDF puts more than one blank line between songs on the same page,
 *       or the page-boundary join happens to land next to an existing
 *       blank line, detection can still be off. It is a best-effort guess,
 *       expected to need eyeballing and possibly {@code --mode page}
 *       instead for a given source file.
 *   <li>{@code page}: treats every PDF page as exactly one song. Simpler
 *       and more predictable for songbooks laid out one-song-per-page, but
 *       wrong for anything else.
 * </ul>
 *
 * <p>Within a detected block, the first non-blank line is assumed to be
 * the title and the second the artist (swap with {@code --artist-first}),
 * and everything after that is stored verbatim as the chords/lyrics blob.
 * This is also just a default assumption -- there is no universal
 * convention for how these books lay out title vs. artist, so check your
 * own output.
 *
 * <p><b>Encoding warning:</b> PDFBox extracts whatever character mapping
 * the PDF's fonts declare. Old, especially scanned-then-typeset PDFs from
 * this era sometimes have subtly wrong font encodings that render
 * correctly on screen (a human reading the rendered glyphs sees the right
 * letter) but extract as the wrong Unicode code point via text extraction.
 * This tool always writes UTF-8, but that doesn't guarantee the
 * *extracted* text was correct to begin with. <b>Spot-check a sample of
 * the output files for mangled š/đ/č/ć/ž before trusting the whole
 * batch</b> -- don't assume a clean run means clean data.
 */
public final class SongbookPdfImporter {

    // Two or more consecutive blank lines (allowing trailing whitespace on
    // an otherwise-blank line): song separator for --mode blank-lines.
    private static final Pattern SONG_SEPARATOR = Pattern.compile("\\n[ \\t]*\\n[ \\t]*\\n+");

    // Characters that are unsafe/awkward in filenames across common
    // filesystems. Applied to artist/title before they become part of the
    // ".tab" filename (TextFileSongRepository itself does no sanitization
    // -- its callers so far have always been trusted in-app data).
    private static final Pattern FILENAME_UNSAFE = Pattern.compile("[\\\\/:*?\"<>|\\p{Cntrl}]");

    private SongbookPdfImporter() {
    }

    public static void main(String[] args) throws IOException {
        Options options = Options.parse(args);
        if (options == null) {
            printUsage();
            return;
        }

        List<PageText> pages = extractPages(options.pdfPath);
        List<ParsedSong> songs = "page".equals(options.mode)
                ? splitByPage(pages)
                : splitByBlankLines(pages);

        if (options.dryRun) {
            printDryRunReport(songs);
            return;
        }

        Files.createDirectories(options.outputDir);
        TextFileSongRepository repository = new TextFileSongRepository(options.outputDir);
        int written = 0;
        for (ParsedSong song : songs) {
            if (song.isUsable()) {
                String artist = options.artistFirst ? song.firstLine : song.secondLine;
                String title = options.artistFirst ? song.secondLine : song.firstLine;
                repository.save(new Song(sanitize(artist), sanitize(title), song.body));
                written++;
            }
        }
        System.out.printf(
                "Wrote %d of %d detected song(s) to %s (%d skipped: too short to contain a title/artist/body split).%n",
                written, songs.size(), options.outputDir.toAbsolutePath(), songs.size() - written);
        System.out.println("Spot-check several output files for garbled diacritics (š đ č ć ž) before trusting the batch -- see this class's Javadoc.");
    }

    private static String sanitize(String text) {
        return FILENAME_UNSAFE.matcher(text.trim()).replaceAll("_");
    }

    // ------------------------------------------------------------------
    // PDF text extraction
    // ------------------------------------------------------------------

    // Package-private (not private): SongbookPdfImporterTest constructs
    // these directly to unit-test the blank-line-run splitting heuristic
    // deterministically, without going through an actual PDF round-trip
    // (real-world PDF text extraction doesn't reliably preserve fully
    // blank lines -- see that test class for why).
    record PageText(int pageNumber, String text) {
    }

    private static List<PageText> extractPages(Path pdfPath) throws IOException {
        List<PageText> pages = new ArrayList<>();
        try (PDDocument document = PDDocument.load(pdfPath.toFile())) {
            PDFTextStripper stripper = new PDFTextStripper();
            int pageCount = document.getNumberOfPages();
            for (int page = 1; page <= pageCount; page++) {
                stripper.setStartPage(page);
                stripper.setEndPage(page);
                pages.add(new PageText(page, stripper.getText(document)));
            }
        }
        return pages;
    }

    // ------------------------------------------------------------------
    // Song-boundary detection
    // ------------------------------------------------------------------

    // Package-private for the same reason as PageText above.
    record ParsedSong(String firstLine, String secondLine, String body, int startPage, int endPage) {

        boolean isUsable() {
            return firstLine != null && !firstLine.isBlank()
                    && secondLine != null && !secondLine.isBlank()
                    && body != null && !body.isBlank();
        }
    }

    static List<ParsedSong> splitByPage(List<PageText> pages) {
        List<ParsedSong> songs = new ArrayList<>();
        for (PageText page : pages) {
            if (page.text().isBlank()) {
                continue;
            }
            songs.add(toParsedSong(page.text(), page.pageNumber(), page.pageNumber()));
        }
        return songs;
    }

    static List<ParsedSong> splitByBlankLines(List<PageText> pages) {
        // Join pages with a single blank line so a page break alone never
        // creates the 2-blank-line run that SONG_SEPARATOR looks for --
        // see the class Javadoc's note on multi-page songs.
        StringBuilder combined = new StringBuilder();
        List<Integer> pageStartOffsets = new ArrayList<>();
        List<Integer> pageNumbers = new ArrayList<>();
        for (PageText page : pages) {
            pageStartOffsets.add(combined.length());
            pageNumbers.add(page.pageNumber());
            combined.append(page.text());
            combined.append("\n\n");
        }

        String[] blocks = SONG_SEPARATOR.split(combined.toString());
        List<ParsedSong> songs = new ArrayList<>();
        int searchFrom = 0;
        for (String block : blocks) {
            if (block.isBlank()) {
                continue;
            }
            int blockStart = combined.indexOf(block, searchFrom);
            int blockEnd = blockStart + block.length();
            searchFrom = blockEnd;
            int startPage = pageNumberForOffset(pageStartOffsets, pageNumbers, blockStart);
            int endPage = pageNumberForOffset(pageStartOffsets, pageNumbers, blockEnd - 1);
            songs.add(toParsedSong(block, startPage, endPage));
        }
        return songs;
    }

    private static int pageNumberForOffset(List<Integer> pageStartOffsets, List<Integer> pageNumbers, int offset) {
        int result = pageNumbers.get(0);
        for (int i = 0; i < pageStartOffsets.size(); i++) {
            if (pageStartOffsets.get(i) <= offset) {
                result = pageNumbers.get(i);
            } else {
                break;
            }
        }
        return result;
    }

    private static ParsedSong toParsedSong(String blockText, int startPage, int endPage) {
        List<String> lines = new ArrayList<>();
        for (String line : blockText.split("\n", -1)) {
            if (!line.isBlank()) {
                lines.add(line.trim());
            } else if (!lines.isEmpty()) {
                // Preserve blank lines *within* the body once we've seen
                // the first two non-blank lines (title/artist) -- they're
                // meaningful line breaks in the chords/lyrics layout.
                lines.add("");
            }
        }
        // Drop leading blank lines collected before the title was found.
        while (!lines.isEmpty() && lines.get(0).isEmpty()) {
            lines.remove(0);
        }
        if (lines.size() < 3) {
            String first = lines.size() > 0 ? lines.get(0) : null;
            String second = lines.size() > 1 ? lines.get(1) : null;
            return new ParsedSong(first, second, null, startPage, endPage);
        }
        String firstLine = lines.get(0);
        String secondLine = lines.get(1);
        String body = String.join("\n", lines.subList(2, lines.size())).strip();
        return new ParsedSong(firstLine, secondLine, body, startPage, endPage);
    }

    // ------------------------------------------------------------------
    // Reporting
    // ------------------------------------------------------------------

    private static void printDryRunReport(List<ParsedSong> songs) {
        long usable = songs.stream().filter(ParsedSong::isUsable).count();
        System.out.printf("Detected %d block(s), %d usable (have a title, artist, and body), %d too short to use.%n",
                songs.size(), usable, songs.size() - usable);
        System.out.println("Page ranges and body lengths only -- no extracted text is printed by --dry-run:");
        for (int i = 0; i < songs.size(); i++) {
            ParsedSong song = songs.get(i);
            String pageRange = song.startPage == song.endPage
                    ? "page " + song.startPage
                    : "pages " + song.startPage + "-" + song.endPage;
            int bodyChars = song.body == null ? 0 : song.body.length();
            System.out.printf("  [%d] %s, body length %d chars%s%n",
                    i + 1, pageRange, bodyChars, song.isUsable() ? "" : " (SKIPPED: not usable)");
        }
    }

    // ------------------------------------------------------------------
    // CLI argument parsing
    // ------------------------------------------------------------------

    private record Options(Path pdfPath, Path outputDir, boolean dryRun, String mode, boolean artistFirst) {

        static Options parse(String[] args) {
            Path pdfPath = null;
            Path outputDir = Paths.get("imported");
            boolean dryRun = false;
            String mode = "blank-lines";
            boolean artistFirst = false;

            for (int i = 0; i < args.length; i++) {
                switch (args[i]) {
                    case "--pdf" -> pdfPath = expandHome(args[++i], System.getProperty("user.home"));
                    case "--output-dir" -> outputDir = expandHome(args[++i], System.getProperty("user.home"));
                    case "--dry-run" -> dryRun = true;
                    case "--mode" -> mode = args[++i];
                    case "--artist-first" -> artistFirst = true;
                    case "--help", "-h" -> {
                        return null;
                    }
                    default -> {
                        System.err.println("Unknown argument: " + args[i]);
                        return null;
                    }
                }
            }

            if (pdfPath == null) {
                System.err.println("Missing required --pdf <path>");
                return null;
            }
            if (!"blank-lines".equals(mode) && !"page".equals(mode)) {
                System.err.println("Invalid --mode: " + mode + " (expected 'blank-lines' or 'page')");
                return null;
            }
            return new Options(pdfPath, outputDir, dryRun, mode, artistFirst);
        }
    }

    // A leading "~" is only expanded by the shell, and only when unquoted
    // -- inside -Dexec.args="--pdf ~/Downloads/x.pdf" it's passed through
    // literally, which java.nio.file.Path has no special handling for
    // (unlike a shell). Expand it ourselves so the natural way to type
    // this doesn't silently look in the wrong place. Package-private (not
    // private) so SongbookPdfImporterTest can verify it directly against
    // a fixed home directory, without needing to write into the real
    // $HOME during a test.
    static Path expandHome(String rawPath, String homeDir) {
        if (rawPath.equals("~") || rawPath.startsWith("~/")) {
            return Paths.get(homeDir, rawPath.substring(1));
        }
        return Paths.get(rawPath);
    }

    private static void printUsage() {
        System.out.println("""
                Usage: SongbookPdfImporter --pdf <path> [options]

                Splits a songbook PDF into .tab files (see this class's Javadoc for the
                song-boundary detection heuristics and their limitations).

                Options:
                  --pdf <path>        Required. Path to the source PDF.
                  --output-dir <path> Directory to write .tab files into. Defaults to
                                      ./imported -- deliberately NOT the app's live
                                      vinoigitare.songs-dir, so a first attempt can't
                                      clobber real data. Point --output-dir at the real
                                      songs directory yourself once you've checked the
                                      output.
                  --dry-run           Report detected song count and page ranges/body
                                      lengths only -- writes nothing, prints no
                                      extracted title/artist/lyric text.
                  --mode <mode>       'blank-lines' (default) or 'page'. See Javadoc.
                  --artist-first      Swap the default assumption (title first, artist
                                      second) if your source has them the other way
                                      around.
                  --help              Show this message.

                Example:
                  ./mvnw compile exec:java -Dexec.mainClass=com.vinoigitare.tools.SongbookPdfImporter \\
                      -Dexec.args="--pdf ~/Downloads/Vino_i_gitare.pdf --dry-run"
                """);
    }
}
